### PR TITLE
Add support for 8.2

### LINKED ISSUE #6: Add support for 8.2
Please add new images for 8.2

### PR DESCRIPTION
**Pull request by samlitowitz**
Resolves #6

### CODE REVIEW

**Comment by samlitowitz** [comment]
@pszalko for visibility.

**Comment by pszalko** [comment]
Thanks @samlitowitz 
It looks good :)

I’ll review and merge it soon after holidays.

**Comment by samlitowitz** [comment]
I've added two pieces to this since you've commented.

One piece is having version dependent Xdebug configuration (`xdebug-2.ini`, `xdebug-3.ini`).
The other is adding newline at the end of the `Dockerfile` and both Xdebug configurations.

**Comment by samlitowitz** [comment]
@pszalko It's been a month, is there any blockers that I can address?

**Comment by samlitowitz** [comment]
@pszalko Reaching out to see if there is an ETA on reviewing or getting feedback on this.

**Review by pszalko — APPROVED** [review]

**Comment by pszalko** [comment]
@samlitowitz Merged :) Thank you for your support and patience!

**Pull request merged**
